baseURL = "https://crunch-io.github.io/crunchy/newsite/"
languageCode = "en-us"
title = "Crunch"
theme = "landing-page-hugo"
relativeURLs = true


[params]
description = "A modern platform"
description2 = "for analytics"
