#!/bin/bash
/var/lib/crunch.io/venv/bin/cr.server.load_data /var/lib/crunch.io/cr.server-0.conf /var/lib/crunch.io/src/backend-http/cr/server/fixtures/
curl -XDELETE 'http://localhost:9200/crunch_app_db_prod_variables*'
mongo crunch_app_db_prod reset_mongo.js
s3cmd rm --recursive s3://percioustest/ --force
rm -rf /var/lib/crunch.io/zz9data/*
#rm -rf /tmp/fake_s3/testing_bucket/*
redis-cli FLUSHALL
echo 'RESTARTING ZZ9...'
supervisorctl restart zz9:*
echo 'RESTARTED, sleeping 30 secs for restart to finish'
sleep 30
echo 'Done, setting up index'
/var/lib/crunch.io/venv/bin/cr.index /var/lib/crunch.io/cr.server-0.conf --create-only --update-alias --clear
echo 'Bootstrapping'
CR_LOGLEVEL=1 /var/lib/crunch.io/venv/bin/python ./bootstrap.py /var/lib/crunch.io/cr.server-0.conf
/var/lib/crunch.io/venv/bin/cr.index /var/lib/crunch.io/cr.server-0.conf
