service: pivotal
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  lambdaHashingVersion: 20201221
  versionFunctions: false
  apiGateway:
    shouldStartNameWithService: true
  environment:
#    env variables will be passed in via .env file so we don't store them in source repository
#    PIVOTAL_PROJECT_ID: abc
#    PIVOTAL_API_KEY: abc
#    SENDGRID_API_KEY: abc

functions:
  webhook-post:
    description: This function is fronted by an api gateway url which pivotal tracker POSTs to every time a pivotal story is updated.
    handler: handler.pivotalStoryWebhook
    #   Normal memory usage is 80MB so set 128MB as max
    memorySize: 128
    #   Normal time needed is 900ms so set 20 seconds as max
    timeout: 20
    events:
      - http:
          path: pivotal
          method: post
  recently-accepted-stories:
    description: Returns a csv file containing recently accepted stories
    handler: handler.recentlyAcceptedStories
    #   Normal memory usage is 80MB so set 128MB as max
    memorySize: 512
    #   Normal time needed is 900ms so set 20 seconds as max
    timeout: 20
    events:
      - http:
          path: pivotal/recently-accepted-stories
          method: get
